#!/bin/bash 
# --------------------------------------------------- 
# Thumbnailer for WPS documents 
# 
# Procedure : 
#   http://bernaerts.dyndns.org/linux/76-gnome/325-gnome-shell-generate-msoffice-thumbnail-nautilus 
# Depends on : 
#   * unoconv (unoconv package)
#   * gvfs-copy (gvfs-bin package) 
#   * convert and composite (imagemagick package) 
#   * mimetype (libfile-mimeinfo-perl package)
# Parameters : 
#   $1 - URI of office file 
#   $2 - full path of generated thumbnail 
#   $3 - height of thumbnail in pixels 
# Revision history : 
# 15/08/2015, V1.0 - Creation by Lorenzo Carbonell
# --------------------------------------------------- 

# check tools availability 
command -v gvfs-copy >/dev/null 2>&1 || exit 1 
command -v unoconv >/dev/null 2>&1 || exit 1 
command -v convert >/dev/null 2>&1 || exit 1 
command -v composite >/dev/null 2>&1 || exit 1 
command -v mimetype >/dev/null 2>&1 || exit 1 

# path where to get icons used for generation 
ICONPATH="/opt/extras.ubuntu.com/wps-thumbnailer/pixmaps" 

# get parameters 
FILE_URI=$1 
FILE_THUMB=$2 
HEIGHT=$3 

# get filename extension 
FILE_EXT=$(echo "$FILE_URI" | sed 's/^.*\.\(.*\)/\1/') 

# generate temporary directory 
TMP_DIR=$(mktemp -d) 
TMP_BASEFILE="$TMP_DIR/file" 

# copy file to temporary local directory 
gvfs-copy "${FILE_URI}" "${TMP_BASEFILE}.${FILE_EXT}" 

# get the file mime type (application/msword, ...)
MIMETYPE=$(mimetype -b "${TMP_BASEFILE}.${FILE_EXT}")

# determine icon type according to mime type 
case $MIMETYPE in
  "application/wps-office.wps" | \
  "application/wps-office.wpt")
    DOCTYPE="wps-writer.png"
    MASK="wps-mask.png"
    ;;
  "application/wps-office.et" | \
  "application/wps-office.ett")
    DOCTYPE="wps-spreadsheet.png"
    MASK="wps-mask.png"
    ;;
  "application/wps-office.dps" | \
  "application/wps-office.dpt")
    DOCTYPE="wps-presentation.png"
    MASK="wps-mask.png"
    ;;
  "application/msword" | "application/vnd.ms-word" | \
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document" )
    DOCTYPE="msoffice-word.png"
    MASK="msoffice-mask.png"
    ;;
  "application/vnd.ms-excel" | \
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" | \
  "application/vnd.openxmlformats-officedocument.spreadsheetml.template" )
    DOCTYPE="msoffice-excel.png"
    MASK="msoffice-mask.png"
    ;;
  "application/vnd.ms-powerpoint" | \
  "application/vnd.openxmlformats-officedocument.presentationml.presentation" | \
  "application/vnd.openxmlformats-officedocument.presentationml.template" | \
  "application/vnd.openxmlformats-officedocument.presentationml.slideshow" )
    DOCTYPE="msoffice-powerpoint.png"
    MASK="msoffice-mask.png"
    ;;
  * )
esac

# convert first document page to PDF 
unoconv -e PageRange=1-1 -f pdf "${TMP_BASEFILE}.${FILE_EXT}" 

# convert PDF to PNG 
convert "${TMP_BASEFILE}.pdf" "${TMP_BASEFILE}.png" 

# generate thumbnail according to document type 
composite -gravity center \( -resize x244 "${TMP_BASEFILE}.png" \) ${ICONPATH}/${DOCTYPE} ${ICONPATH}/${MASK} \( -resize x${HEIGHT} \) "$FILE_THUMB" 

# remove temporary files 
rm -R $TMP_DIR 

