#!/bin/bash 
# --------------------------------------------------- 
# Thumbnailer for WPS documents 
# 
# Procedure : 
#   http://bernaerts.dyndns.org/linux/76-gnome/325-gnome-shell-generate-msoffice-thumbnail-nautilus 
# Depends on : 
#   * unoconv (unoconv package)
#   * gvfs-copy (gvfs-bin package) 
#   * convert and composite (imagemagick package) 
#   * mimetype (libfile-mimeinfo-perl package)
# Parameters : 
#   $1 - URI of office file 
#   $2 - full path of generated thumbnail 
#   $3 - height of thumbnail in pixels 
# Revision history : 
# 15/08/2015, V1.0 - Creation by Lorenzo Carbonell
# --------------------------------------------------- 

# check tools availability 
command -v gvfs-copy >/dev/null 2>&1 || exit 1 
command -v unoconv >/dev/null 2>&1 || exit 1 
command -v convert >/dev/null 2>&1 || exit 1 
command -v composite >/dev/null 2>&1 || exit 1 
command -v mimetype >/dev/null 2>&1 || exit 1 

# path where to get icons used for generation 
ICONPATH="/opt/extras.ubuntu.com/wpsthumbnailer/pixmaps" 

# get parameters 
FILE_URI=$1 
FILE_THUMB=$2 
HEIGHT=$3 

# get filename extension 
FILE_EXT=$(echo "$FILE_URI" | sed 's/^.*\.\(.*\)/\1/') 

# generate temporary directory 
TMP_DIR=$(mktemp -d) 
TMP_BASEFILE="$TMP_DIR/file" 

# copy file to temporary local directory 
gvfs-copy "${FILE_URI}" "${TMP_BASEFILE}.${FILE_EXT}" 

# determine icon type according to mime type 
case `mimetype --brief "$1"` in
  application/wps-office.wps | \
  application/wps-office.wpt)
    DOCTYPE="writer"
    ;;
  application/wps-office.et | \
  application/wps-office.ett)
    DOCTYPE="spreadsheet"
    ;;
  application/wps-office.dps | \
  application/wps-office.dpt)
    DOCTYPE="presentation"
    ;;
  *)
esac

# convert first document page to PDF 
unoconv -e PageRange=1-1 -f pdf "${TMP_BASEFILE}.${FILE_EXT}" 

# convert PDF to PNG 
convert "${TMP_BASEFILE}.pdf" "${TMP_BASEFILE}.png" 

# generate thumbnail according to document type 
composite -gravity center \( -resize x244 "${TMP_BASEFILE}.png" \) ${ICONPATH}/wps-${DOCTYPE}.png ${ICONPATH}/wps-mask.png \( -resize x${HEIGHT} \) "$FILE_THUMB" 

# remove temporary files 
rm -R $TMP_DIR 

